### PR TITLE
Handle hyphenated shex filenames correctly in @ldo/cli

### LINKED ISSUE #89: ldo build fails when shex filename has hyphen eg. catalog-shacl.shex
```bash
SyntaxError: ',' expected. (8:21)
   6 |  * =============================================================================
   7 |  */
>  8 | export const catalog-shaclContext: LdoJsonldContext = {
     |                     ^
   9 |   "name": {
  10 |     "@id": "http://example.org/#name",
  11 |     "@type": "http://www.w3.org/2001/XMLSchema#string"
```

after renaming to something without hyphen in the filename it works fine.

This came up while working on
* https://github.com/solid/catalog/issues/14

### PR DESCRIPTION
**Pull request by mrkvon**
Fixes #89

### CODE REVIEW

File: packages/schema-converter-shex/src/index.ts [hunk 1]
```diff
@@ -1,3 +1,6 @@
 import { shexjToTyping } from "./typing/shexjToTyping";
+import { toCamelCase } from "./context/JsonLdContextBuilder.js";
```
Comment (jaxoncreed) [inline packages/schema-converter-shex/src/index.ts]: Instead of this, change this and the one in context builder to use an NPM library.

**Review by jaxoncreed — CHANGES_REQUESTED** [review]

File: packages/schema-converter-shex/src/index.ts (hunk 1 above)
Comment (mrkvon) [reply packages/schema-converter-shex/src/index.ts]: Addressed with https://www.npmjs.com/package/camelcase in b16b3a6bc0be12b197b262eaf843e652a3ba8c35.

Comment (mrkvon) [reply packages/schema-converter-shex/src/index.ts]: ... but they're not equivalent. Another try...

Comment (mrkvon) [reply packages/schema-converter-shex/src/index.ts]: In order to avoid breaking changes, I've kept original `toCamelCase` in schema-converter-shex, due to its custom behaviour.

@ldo/cli uses [`camelcase`](https://www.npmjs.com/package/camelcase) npm library.

6ebfe9535c189efb852ddc280953c9c71a46e39d

**Review by jaxoncreed — APPROVED** [review]
LGTM
